language: shell
os: linux
dist: focal
before_install:
  - echo "This is a simple .travis.yml file for shell."

script:
  - echo "Hello, Travis CI!"
  - echo "This is a simple build script."
  - echo "You can add your build commands here."
