os: linux
dist: focal
language: shell
vault:
  token:
    secure: "w+nPM4h3gZddEOy7x4ltxHZmUS6R0rTGkuEfZuwgAbLkMQLRpimGQr5gdjnRHj99yuh3HMVG4kcyO2AbQgwhRa37ZGP6yOnPvb9Ty9Z6JTy8fDA+KOBPT6cNvjMrpX5nmWtp0WlwdoWGxooilT1AiX/LsgmrdqgXRpTfVCXVC1rAltZfXpsuay4nzzebTdevmNobNLCBGlJuE1vJcFtFgBK0tTNTR/bAeLW/zXsbTJHrux3Dhv2IoUfsSCfwka5e4xGqfEFqdNjgIo3I0EPbmWDpqqwGfBSmvFsKCJkQaCaTbSiHhSQydH2JO0fF+k0OmSQ4Pa2rwfqSNolrVFs0OlZU1EBaiYXN2KtXYTqSr1EbQdxqDkhA7KkACRfvVgWADwoRY2IMbl88C6mAlWWYtpBC3tn+G3lKbVgRxGeVw0J0rkFFl6jik2WWZX217hFfZ41J4uNSVVSSU+ITpFF6rqqJJJ38BhhVVz0FeJa249H8+9JbI8DN7P8eDgBpgrvYQLrmf+rugCjJS/kiCDQfh9/Nh82Sl/ey3yrXLpfh1q8NNGKMfzURIWxtcEiXh3hYu97ppJF/H5dZGi/U8/m/QrS/Q0p/CXFSN4N8/7aydgW4xu1e0Nuv5ATdxgVX1HVCTGUltKrU3kSQBv9fsKe1S1+X6RnynTDPuOd6S1ZufOg="
  api_url: https://vault-dwztla.travis-ci.com
  secrets:
    - 4ibm

script:
  - echo $4ibm_foo
#this adds comment
