os: linux
dist: focal
language: shell
env: 
  global:
   # - FOO=a
    - BAR=B
install: skip
script: sleep 1

jobs: 
  include: 
    - if: env(FOO) =~ [abc] and env(BAR) =~ [ABC]
    - if: env(FOO) =~ [abc] or env(BAR) =~ [ABC]
    - if: env(FOO) =~ [ABC]
    - if: env(BAR) =~ [abc]
    - if: env(FOO) =~ [ABC] and env(BAR) =~ [ABC]
    - if: env(FOO) =~ [abc] or env(BAR) =~ [abc]
