os: linux
dist: focal
language: shell
env:
  global:
    - BAR=true


install: skip

jobs:
  include:
    - name: "condition with regex"
      script: echo "condition with regex"
      if: env(BAR) =~ /^(?i)(false|0).*/
    - name: "condition-without-regex"
      script: echo "condition without regex"
      if: env(BAR) =~ [ABC]
