os: linux
dist: focal
language: shell
env: 
  global:
   # - FOO=a
    - BAR=false
install: skip

 

jobs: 
  include:
    - stage: "STAGE A"
      name: "STAGE A"
      script: sleep 1

      if: env(BAR) = false
    - stage: "STAGE A"
      name: "STAGE A"
      script: sleep 2

      if: env(BAR) = false
    - stage: "STAGE B"
      name: "STAGE A"
      script: sleep 3

      if: env(BAR) = true
    - stage: "STAGE B"
      name: "STAGE A"
      script: sleep 4

      if: env(BAR) = true
