os: linux
dist: focal
language: shell
vault:
  token:
    secure: "CeUSoyxxNn+Th/zs+cATw+Wi2F0v7JmgTaYHv5OagsgNenaIxCnjGrD9/Q8LzTBgOpAl4+xnczqVk98bpNME+RAY7OwsGvCRHe6Q5p5WyMxr6MWnU7owI0z/Xk+kamaRiyeiAtJ/KjFGOf5jhVx4g619rAQiyG+yD0Aq++2TLXR8n8oWjlypmr2y5hvMTmuSk0OBaz4Kdcw/HzFRp+bBn+7yM79l+vUNRJjLudL+gzlGM8xkBOLzl0a7/lG0UEKsCGRMsR+iak0JDK+QU41Pkz/zgyV7C48Ec7tTqgfxkbZzsmF4pcuW9EthtC1YwznGhPKdbGzUsfjMFLyb4UGlCRVuzerFCdxK5LibGDnLB+RxYAlduyW46LceSJXswrq4duiKBa2duseX4FkZ+SnYpcbftB3ZKpla6jbzr+DLAL017iNzRWk6SrfNW1Mc+5RaHf5zPf8+h12WgBITCs0FOeZUkAcinGlW8rm97u8SvSWjCjFE5aiYZU6ETkXjxdNMkbThkkCKZ6VswA73bnxDNzmOuwdQl6i9P16cmP62lDrNolKTVgk84nU6uEyFJ4eQD5/B6Mj+zI36PrKXuAHLXc5cP3e/iv7lNKBJj2SSJgNm9u2PldClaOvYHfAEvXQovrNomcJzbzGvbLrHE961v/cG50Zsg5/D0u0xivp06iU="
  secrets:
    - 4ibm

script:
  - echo $4ibm_foo
#this adds comment
