os: linux
dist: focal
language: python

stages:
  - build
  - test
  - deploy

jobs:
  build:
    script:
      - sleep 1000

  test:
    script:
      - sleep 1000

  deploy:
    script:
      - sleep 1000

pip:
  version: 20.2
  use-feature: 2020-resolver

install:
  - pip install -r requirements.txt

script:
  - python test.py
