os: linux
dist: focal
language: python

stages:
  - build
  - test
  - deploy

jobs:
  build:
    script:
      - sleep 1000

  test:
    script:
      - sleep 1000

  deploy:
    script:
      - sleep 1000
