os: linux
dist: focal
language: shell

jobs:
  include:
    - vault:
      token: $VAULTSEC
      api_url: https://vault-east.staging.travis-ci.org
      secrets:
        - ibmhashicorp
    - vault:
      token: $VAULTSEC
      api_url: https://vault-east.staging.travis-ci.org
      secrets:
        - ibmhashicorp/foo

 

script:
  - echo $API_TEST_HASHICORP_IBM_FOO
