os: linux
dist: focal
language: shell
vault:
  token:
    secure: secure: "nUGv3VaGTpR/o2Hd9WYo2C5qC9wPtmbwpWNh3p4MlabDlQUXVbkuDcg5eD657PKHNIwnkMMa1ADXh+1XIkMSLcfeZf8ThbyqiGOjQEZDMZ/jY/lUvGGmv3ovGXoZGBoRq9c6hOoN1CJghhepWsHPAnIQRWcb7tlfUy7a1u2E8W4QcB6+DlyJxSUnIWTCOowgFSG6IqoySKBrpYGXBCE+VzeInuw4vhx7Nj2lRW9gt9KKvRqOasvsqMm94PK3eo9FB+3Pr+MiDxC9twyLrUmLKsCcyAMiEiMyK3eMMYy+u3nDw/4irhUZlkc+TrXZa0AS66WkvUJdspSoFYzmo5JbOuRTHE9oQbJ+Mx+VFDi5D3JJUKrox3tOE6nZATAToMPKHbtrr1FRNlgnynucVRWAPjuGvzEGE6cx8lBci9PqJe9e3Emb5vb9RJedEeHvZCFewwrUGvyHvzNhqo7uinlFz3axeRFWOyPNlvU7/FmXGXqJkhyh6R9lZY41T7LuNte1E5bfmaJZJi6DmZ/g7A6cwt59Y5MQLwplHyn01Jn9SOstJx7t8jtGPiHoaYk5QZynBoTWvdKkqsF83gXSdov+yd80nTN/YUAEzOWatmJyrOrRVjKlDNNC+F9PnwSJaPOJel8uzQI9QLryY1mVgAh7nXT9oSMs03BKwTzYd3oSB6M="
  api_url: https://vault-east.staging.travis-ci.org 
  secrets:
    - secret/ibmhashicorp/foo

script:
  - echo $ibmhashicorp_foo
#this adds comment
