language: python

matrix:
  include:
    - os: linux
      env:
        - TRAVIS_GOOS=darwin
        - TRAVIS_CGO_ENABLED=0
    - os: osx
      env:
        - TRAVIS_GOOS=linux
        - TRAVIS_CGO_ENABLED=1

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      echo "Setting environment variables for Linux";
      export MY_CUSTOM_ENV_VAR=linux_value;
    else
      echo "Setting environment variables for macOS";
      export MY_CUSTOM_ENV_VAR=osx_value;
    fi

script:
  - echo "Running script on $TRAVIS_OS_NAME"
  - echo "MY_CUSTOM_ENV_VAR value: $MY_CUSTOM_ENV_VAR"
  - echo "TRAVIS_GOOS value: $TRAVIS_GOOS"
  - echo "TRAVIS_CGO_ENABLED value: $TRAVIS_CGO_ENABLED"
